/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgentInput = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'agentRole' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const ProductType = IDL.Variant({
  'agriProduct' : IDL.Null,
  'kitchenGarden' : IDL.Null,
  'machine' : IDL.Null,
});
export const CustomerOrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerMobile' : IDL.Text,
  'productId' : IDL.Text,
  'productType' : ProductType,
  'customerAddress' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'customerMobile' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'productType' : ProductType,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'productSummary' : IDL.Text,
});
export const Category = IDL.Variant({
  'seed' : IDL.Null,
  'kitchenGarden' : IDL.Null,
  'pesticide' : IDL.Null,
  'herbicide' : IDL.Null,
  'machine' : IDL.Null,
  'plantGrowthRegulator' : IDL.Null,
  'fungicide' : IDL.Null,
  'insecticide' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'stock' : IDL.Nat,
  'minimumOrderQuantity' : IDL.Nat,
  'category' : Category,
  'translations' : IDL.Record({
    'name' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'description' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  }),
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const AboutUsContentTranslationsView = IDL.Record({
  'title' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'content' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const Agent = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'agentRole' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const ImmutableMap = IDL.Record({
  'entries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ProductView = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'stock' : IDL.Nat,
  'minimumOrderQuantity' : IDL.Nat,
  'category' : Category,
  'translations' : IDL.Record({
    'name' : ImmutableMap,
    'description' : ImmutableMap,
  }),
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LandingPageTranslationsView = IDL.Record({
  'heroSubtitle' : ImmutableMap,
  'heroTitle' : ImmutableMap,
});
export const ReferenceWebsite = IDL.Record({
  'url' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'agentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgent' : IDL.Func([IDL.Text, AgentInput, IDL.Principal], [], []),
  'createCustomerOrder' : IDL.Func(
      [CustomerOrderInput],
      [IDL.Opt(CustomerOrder)],
      [],
    ),
  'createProduct' : IDL.Func([IDL.Text, ProductInput], [], []),
  'deleteAgent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAboutUs' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AboutUsContentTranslationsView)],
      ['query'],
    ),
  'getAgent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Agent)], ['query']),
  'getAgentOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getAllAgents' : IDL.Func([IDL.Text], [IDL.Vec(Agent)], ['query']),
  'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(ProductView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrder' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CustomerOrder)],
      ['query'],
    ),
  'getKitchenGardenProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'getLandingPageTranslations' : IDL.Func(
      [IDL.Text],
      [LandingPageTranslationsView],
      ['query'],
    ),
  'getMachineProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [IDL.Vec(CustomerOrder)],
      ['query'],
    ),
  'getProductTranslations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ProductView)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [Category, IDL.Text],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'getReferenceWebsite' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReferenceWebsite)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setReferenceWebsite' : IDL.Func([IDL.Text, ReferenceWebsite], [], []),
  'updateAboutUsTranslation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateAgent' : IDL.Func([IDL.Text, IDL.Text, AgentInput], [], []),
  'updateLandingPageTranslation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, IDL.Text, ProductInput], [], []),
  'updateProductTranslations' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgentInput = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'agentRole' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  const ProductType = IDL.Variant({
    'agriProduct' : IDL.Null,
    'kitchenGarden' : IDL.Null,
    'machine' : IDL.Null,
  });
  const CustomerOrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerMobile' : IDL.Text,
    'productId' : IDL.Text,
    'productType' : ProductType,
    'customerAddress' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'customerMobile' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'productType' : ProductType,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'productSummary' : IDL.Text,
  });
  const Category = IDL.Variant({
    'seed' : IDL.Null,
    'kitchenGarden' : IDL.Null,
    'pesticide' : IDL.Null,
    'herbicide' : IDL.Null,
    'machine' : IDL.Null,
    'plantGrowthRegulator' : IDL.Null,
    'fungicide' : IDL.Null,
    'insecticide' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'stock' : IDL.Nat,
    'minimumOrderQuantity' : IDL.Nat,
    'category' : Category,
    'translations' : IDL.Record({
      'name' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      'description' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    }),
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const AboutUsContentTranslationsView = IDL.Record({
    'title' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'content' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const Agent = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'agentRole' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  const ImmutableMap = IDL.Record({
    'entries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ProductView = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'stock' : IDL.Nat,
    'minimumOrderQuantity' : IDL.Nat,
    'category' : Category,
    'translations' : IDL.Record({
      'name' : ImmutableMap,
      'description' : ImmutableMap,
    }),
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LandingPageTranslationsView = IDL.Record({
    'heroSubtitle' : ImmutableMap,
    'heroTitle' : ImmutableMap,
  });
  const ReferenceWebsite = IDL.Record({
    'url' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'agentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgent' : IDL.Func([IDL.Text, AgentInput, IDL.Principal], [], []),
    'createCustomerOrder' : IDL.Func(
        [CustomerOrderInput],
        [IDL.Opt(CustomerOrder)],
        [],
      ),
    'createProduct' : IDL.Func([IDL.Text, ProductInput], [], []),
    'deleteAgent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAboutUs' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AboutUsContentTranslationsView)],
        ['query'],
      ),
    'getAgent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Agent)], ['query']),
    'getAgentOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getAllAgents' : IDL.Func([IDL.Text], [IDL.Vec(Agent)], ['query']),
    'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(ProductView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrder' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CustomerOrder)],
        ['query'],
      ),
    'getKitchenGardenProducts' : IDL.Func(
        [],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getLandingPageTranslations' : IDL.Func(
        [IDL.Text],
        [LandingPageTranslationsView],
        ['query'],
      ),
    'getMachineProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [IDL.Vec(CustomerOrder)],
        ['query'],
      ),
    'getProductTranslations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ProductView)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category, IDL.Text],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getReferenceWebsite' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReferenceWebsite)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setReferenceWebsite' : IDL.Func([IDL.Text, ReferenceWebsite], [], []),
    'updateAboutUsTranslation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateAgent' : IDL.Func([IDL.Text, IDL.Text, AgentInput], [], []),
    'updateLandingPageTranslation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, IDL.Text, ProductInput], [], []),
    'updateProductTranslations' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };