/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerOrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerMobile' : IDL.Text,
  'productId' : IDL.Text,
  'customerAddress' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'customerMobile' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'productSummary' : IDL.Text,
});
export const Category = IDL.Variant({
  'seed' : IDL.Null,
  'pesticide' : IDL.Null,
  'herbicide' : IDL.Null,
  'plantGrowthRegulator' : IDL.Null,
  'fungicide' : IDL.Null,
  'insecticide' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'stock' : IDL.Nat,
  'minimumOrderQuantity' : IDL.Nat,
  'category' : Category,
  'translations' : IDL.Record({
    'name' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'description' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  }),
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const ImmutableMap = IDL.Record({
  'entries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ProductView = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'stock' : IDL.Nat,
  'minimumOrderQuantity' : IDL.Nat,
  'category' : Category,
  'translations' : IDL.Record({
    'name' : ImmutableMap,
    'description' : ImmutableMap,
  }),
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LandingPageTranslationsView = IDL.Record({
  'heroSubtitle' : ImmutableMap,
  'heroTitle' : ImmutableMap,
});
export const ReferenceWebsite = IDL.Record({
  'url' : IDL.Text,
  'designNotes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomerOrder' : IDL.Func(
      [CustomerOrderInput],
      [IDL.Opt(CustomerOrder)],
      [],
    ),
  'createProduct' : IDL.Func([ProductInput], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(ProductView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerOrder)],
      ['query'],
    ),
  'getLandingPageTranslations' : IDL.Func(
      [IDL.Text],
      [LandingPageTranslationsView],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(CustomerOrder)],
      ['query'],
    ),
  'getProductTranslations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ProductView)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [Category, IDL.Text],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'getReferenceWebsite' : IDL.Func([], [IDL.Opt(ReferenceWebsite)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setReferenceWebsite' : IDL.Func([ReferenceWebsite], [], []),
  'updateLandingPageTranslation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, ProductInput], [], []),
  'updateProductTranslations' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerOrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerMobile' : IDL.Text,
    'productId' : IDL.Text,
    'customerAddress' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'customerMobile' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'productSummary' : IDL.Text,
  });
  const Category = IDL.Variant({
    'seed' : IDL.Null,
    'pesticide' : IDL.Null,
    'herbicide' : IDL.Null,
    'plantGrowthRegulator' : IDL.Null,
    'fungicide' : IDL.Null,
    'insecticide' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'stock' : IDL.Nat,
    'minimumOrderQuantity' : IDL.Nat,
    'category' : Category,
    'translations' : IDL.Record({
      'name' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      'description' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    }),
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const ImmutableMap = IDL.Record({
    'entries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ProductView = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'stock' : IDL.Nat,
    'minimumOrderQuantity' : IDL.Nat,
    'category' : Category,
    'translations' : IDL.Record({
      'name' : ImmutableMap,
      'description' : ImmutableMap,
    }),
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LandingPageTranslationsView = IDL.Record({
    'heroSubtitle' : ImmutableMap,
    'heroTitle' : ImmutableMap,
  });
  const ReferenceWebsite = IDL.Record({
    'url' : IDL.Text,
    'designNotes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomerOrder' : IDL.Func(
        [CustomerOrderInput],
        [IDL.Opt(CustomerOrder)],
        [],
      ),
    'createProduct' : IDL.Func([ProductInput], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(ProductView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerOrder)],
        ['query'],
      ),
    'getLandingPageTranslations' : IDL.Func(
        [IDL.Text],
        [LandingPageTranslationsView],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(CustomerOrder)],
        ['query'],
      ),
    'getProductTranslations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ProductView)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category, IDL.Text],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getReferenceWebsite' : IDL.Func(
        [],
        [IDL.Opt(ReferenceWebsite)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setReferenceWebsite' : IDL.Func([ReferenceWebsite], [], []),
    'updateLandingPageTranslation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, ProductInput], [], []),
    'updateProductTranslations' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };