/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutUsContentTranslationsView {
  'title' : Array<[string, string]>,
  'content' : Array<[string, string]>,
}
export interface Agent {
  'principal' : Principal,
  'username' : string,
  'password' : string,
  'agentRole' : string,
  'mobileNumber' : string,
}
export interface AgentInput {
  'username' : string,
  'password' : string,
  'agentRole' : string,
  'mobileNumber' : string,
}
export type Category = { 'seed' : null } |
  { 'kitchenGarden' : null } |
  { 'pesticide' : null } |
  { 'herbicide' : null } |
  { 'machine' : null } |
  { 'plantGrowthRegulator' : null } |
  { 'fungicide' : null } |
  { 'insecticide' : null };
export interface CustomerOrder {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'customerMobile' : string,
  'productId' : string,
  'productName' : string,
  'productType' : ProductType,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'productSummary' : string,
}
export interface CustomerOrderInput {
  'customerName' : string,
  'customerMobile' : string,
  'productId' : string,
  'productType' : ProductType,
  'customerAddress' : string,
  'quantity' : bigint,
}
export interface ImmutableMap { 'entries' : Array<[string, string]> }
export interface LandingPageTranslationsView {
  'heroSubtitle' : ImmutableMap,
  'heroTitle' : ImmutableMap,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface ProductInput {
  'id' : string,
  'createdAt' : Time,
  'stock' : bigint,
  'minimumOrderQuantity' : bigint,
  'category' : Category,
  'translations' : {
    'name' : Array<[string, string]>,
    'description' : Array<[string, string]>,
  },
  'price' : bigint,
  'images' : Array<string>,
}
export type ProductType = { 'agriProduct' : null } |
  { 'kitchenGarden' : null } |
  { 'machine' : null };
export interface ProductView {
  'id' : string,
  'createdAt' : Time,
  'stock' : bigint,
  'minimumOrderQuantity' : bigint,
  'category' : Category,
  'translations' : { 'name' : ImmutableMap, 'description' : ImmutableMap },
  'price' : bigint,
  'images' : Array<string>,
}
export interface ReferenceWebsite { 'url' : string, 'description' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'agentLogin' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgent' : ActorMethod<[string, AgentInput, Principal], undefined>,
  'createCustomerOrder' : ActorMethod<
    [CustomerOrderInput],
    [] | [CustomerOrder]
  >,
  'createProduct' : ActorMethod<[string, ProductInput], undefined>,
  'deleteAgent' : ActorMethod<[string, string], undefined>,
  'deleteProduct' : ActorMethod<[string, string], undefined>,
  'getAboutUs' : ActorMethod<[string], [] | [AboutUsContentTranslationsView]>,
  'getAgent' : ActorMethod<[string, string], [] | [Agent]>,
  'getAgentOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getAllAgents' : ActorMethod<[string], Array<Agent>>,
  'getAllProducts' : ActorMethod<[string], Array<ProductView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrder' : ActorMethod<[string, string], [] | [CustomerOrder]>,
  'getKitchenGardenProducts' : ActorMethod<[], Array<ProductView>>,
  'getLandingPageTranslations' : ActorMethod<
    [string],
    LandingPageTranslationsView
  >,
  'getMachineProducts' : ActorMethod<[], Array<ProductView>>,
  'getOrdersByStatus' : ActorMethod<
    [string, OrderStatus],
    Array<CustomerOrder>
  >,
  'getProductTranslations' : ActorMethod<[string, string], [] | [ProductView]>,
  'getProductsByCategory' : ActorMethod<[Category, string], Array<ProductView>>,
  'getReferenceWebsite' : ActorMethod<[string], [] | [ReferenceWebsite]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setReferenceWebsite' : ActorMethod<[string, ReferenceWebsite], undefined>,
  'updateAboutUsTranslation' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateAgent' : ActorMethod<[string, string, AgentInput], undefined>,
  'updateLandingPageTranslation' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[string, string, ProductInput], undefined>,
  'updateProductTranslations' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];