/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerOrder {
    id: string;
    customerName: string;
    status: OrderStatus;
    createdAt: Time;
    customerMobile: string;
    productId: string;
    productName: string;
    customerAddress: string;
    totalAmount: bigint;
    quantity: bigint;
    productSummary: string;
}
export interface ProductInput {
    id: string;
    createdAt: Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: Category;
    translations: {
        name: Array<[string, string]>;
        description: Array<[string, string]>;
    };
    price: bigint;
    images: Array<string>;
}
export type Time = bigint;
export interface ProductView {
    id: string;
    createdAt: Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: Category;
    translations: {
        name: ImmutableMap;
        description: ImmutableMap;
    };
    price: bigint;
    images: Array<string>;
}
export interface LandingPageTranslationsView {
    heroSubtitle: ImmutableMap;
    heroTitle: ImmutableMap;
}
export interface CustomerOrderInput {
    customerName: string;
    customerMobile: string;
    productId: string;
    customerAddress: string;
    quantity: bigint;
}
export interface ImmutableMap {
    entries: Array<[string, string]>;
}
export interface ReferenceWebsite {
    url: string;
    designNotes?: string;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    seed = "seed",
    pesticide = "pesticide",
    herbicide = "herbicide",
    plantGrowthRegulator = "plantGrowthRegulator",
    fungicide = "fungicide",
    insecticide = "insecticide"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomerOrder(customerOrder: CustomerOrderInput): Promise<CustomerOrder | null>;
    createProduct(productInput: ProductInput): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    getAllProducts(arg0: string): Promise<Array<ProductView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerOrder(orderId: string): Promise<CustomerOrder | null>;
    getLandingPageTranslations(arg0: string): Promise<LandingPageTranslationsView>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<CustomerOrder>>;
    getProductTranslations(arg0: string, productId: string): Promise<ProductView | null>;
    getProductsByCategory(category: Category, language: string): Promise<Array<ProductView>>;
    getReferenceWebsite(): Promise<ReferenceWebsite | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setReferenceWebsite(reference: ReferenceWebsite): Promise<void>;
    updateLandingPageTranslation(language: string, title: string, subtitle: string): Promise<void>;
    updateOrderStatus(orderId: string, newStatus: OrderStatus): Promise<void>;
    updateProduct(productId: string, productInput: ProductInput): Promise<void>;
    updateProductTranslations(productId: string, language: string, name: string, description: string): Promise<void>;
}
import type { Category as _Category, CustomerOrder as _CustomerOrder, ImmutableMap as _ImmutableMap, OrderStatus as _OrderStatus, ProductInput as _ProductInput, ProductView as _ProductView, ReferenceWebsite as _ReferenceWebsite, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomerOrder(arg0: CustomerOrderInput): Promise<CustomerOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomerOrder(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomerOrder(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_ProductInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_ProductInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllProducts(arg0: string): Promise<Array<ProductView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrder(arg0: string): Promise<CustomerOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrder(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrder(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandingPageTranslations(arg0: string): Promise<LandingPageTranslationsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandingPageTranslations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandingPageTranslations(arg0);
            return result;
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<CustomerOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductTranslations(arg0: string, arg1: string): Promise<ProductView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductTranslations(arg0, arg1);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductTranslations(arg0, arg1);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category, arg1: string): Promise<Array<ProductView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferenceWebsite(): Promise<ReferenceWebsite | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferenceWebsite();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferenceWebsite();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setReferenceWebsite(arg0: ReferenceWebsite): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReferenceWebsite(to_candid_ReferenceWebsite_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReferenceWebsite(to_candid_ReferenceWebsite_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLandingPageTranslation(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLandingPageTranslation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLandingPageTranslation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: ProductInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProductTranslations(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductTranslations(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductTranslations(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Category_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerOrder_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerOrder): CustomerOrder {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ProductView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductView): ProductView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReferenceWebsite_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferenceWebsite): ReferenceWebsite {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductView]): ProductView | null {
    return value.length === 0 ? null : from_candid_ProductView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferenceWebsite]): ReferenceWebsite | null {
    return value.length === 0 ? null : from_candid_ReferenceWebsite_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerOrder]): CustomerOrder | null {
    return value.length === 0 ? null : from_candid_CustomerOrder_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: _Category;
    translations: {
        name: _ImmutableMap;
        description: _ImmutableMap;
    };
    price: bigint;
    images: Array<string>;
}): {
    id: string;
    createdAt: Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: Category;
    translations: {
        name: ImmutableMap;
        description: ImmutableMap;
    };
    price: bigint;
    images: Array<string>;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        stock: value.stock,
        minimumOrderQuantity: value.minimumOrderQuantity,
        category: from_candid_Category_n15(_uploadFile, _downloadFile, value.category),
        translations: value.translations,
        price: value.price,
        images: value.images
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    designNotes: [] | [string];
}): {
    url: string;
    designNotes?: string;
} {
    return {
        url: value.url,
        designNotes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.designNotes))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _OrderStatus;
    createdAt: _Time;
    customerMobile: string;
    productId: string;
    productName: string;
    customerAddress: string;
    totalAmount: bigint;
    quantity: bigint;
    productSummary: string;
}): {
    id: string;
    customerName: string;
    status: OrderStatus;
    createdAt: Time;
    customerMobile: string;
    productId: string;
    productName: string;
    customerAddress: string;
    totalAmount: bigint;
    quantity: bigint;
    productSummary: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n6(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        customerMobile: value.customerMobile,
        productId: value.productId,
        productName: value.productName,
        customerAddress: value.customerAddress,
        totalAmount: value.totalAmount,
        quantity: value.quantity,
        productSummary: value.productSummary
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seed: null;
} | {
    pesticide: null;
} | {
    herbicide: null;
} | {
    plantGrowthRegulator: null;
} | {
    fungicide: null;
} | {
    insecticide: null;
}): Category {
    return "seed" in value ? Category.seed : "pesticide" in value ? Category.pesticide : "herbicide" in value ? Category.herbicide : "plantGrowthRegulator" in value ? Category.plantGrowthRegulator : "fungicide" in value ? Category.fungicide : "insecticide" in value ? Category.insecticide : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductView>): Array<ProductView> {
    return value.map((x)=>from_candid_ProductView_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerOrder>): Array<CustomerOrder> {
    return value.map((x)=>from_candid_CustomerOrder_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ReferenceWebsite_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReferenceWebsite): _ReferenceWebsite {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    designNotes?: string;
}): {
    url: string;
    designNotes: [] | [string];
} {
    return {
        url: value.url,
        designNotes: value.designNotes ? candid_some(value.designNotes) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: Category;
    translations: {
        name: Array<[string, string]>;
        description: Array<[string, string]>;
    };
    price: bigint;
    images: Array<string>;
}): {
    id: string;
    createdAt: _Time;
    stock: bigint;
    minimumOrderQuantity: bigint;
    category: _Category;
    translations: {
        name: Array<[string, string]>;
        description: Array<[string, string]>;
    };
    price: bigint;
    images: Array<string>;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        stock: value.stock,
        minimumOrderQuantity: value.minimumOrderQuantity,
        category: to_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        translations: value.translations,
        price: value.price,
        images: value.images
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    seed: null;
} | {
    pesticide: null;
} | {
    herbicide: null;
} | {
    plantGrowthRegulator: null;
} | {
    fungicide: null;
} | {
    insecticide: null;
} {
    return value == Category.seed ? {
        seed: null
    } : value == Category.pesticide ? {
        pesticide: null
    } : value == Category.herbicide ? {
        herbicide: null
    } : value == Category.plantGrowthRegulator ? {
        plantGrowthRegulator: null
    } : value == Category.fungicide ? {
        fungicide: null
    } : value == Category.insecticide ? {
        insecticide: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
